name: Dingtalk Notify

on:
  schedule:
    - cron: '10 3 * * 1-5' # 北京时间工作日 11:10 分
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Dingtalk Robot Notify
      uses: leafney/dingtalk-action@v1.1.0
      if: always()
      env:
        DINGTALK_ACCESS_TOKEN: ${{ secrets.DINGTALK_ACCESS_TOKEN }}
      with:
        msgtype: text
        text: '点外卖了'
        at_mobiles: '18270643520'

